### ISSUE TITLE
herokuのbundler/setupが存在しない問題

### ISSUE THREAD

**Issue by YutaGoto** [YutaGoto/salmon_run#30]
```bash
$ heroku run rake db:migrate
Running rake db:migrate on ⬢ salmon-run... up, run.1600 (Free)
rake aborted!
LoadError: cannot load such file -- bundler/setup
/app/config/boot.rb:3:in `<top (required)>'
/app/config/application.rb:1:in `require_relative'
/app/config/application.rb:1:in `<top (required)>'
/app/Rakefile:4:in `require_relative'
/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by YutaGoto** [comment]
herokuの運用を止めてみる。
